- name: Print Parameter from Parameter store
  hosts: localhost
  connection: local
  tasks:
    - name: Print Parameter
      ansible.builtin.debug:
        msg: Parameter - {{ lookup('amazon.aws.aws_ssm', 'firstparameter', region='us-east-1') }}